// ============================================================
// Holidays Database — public holidays for major maritime
// hub countries, for SHEX / laytime calculations.
// 2026 dates. Fixed-date holidays are reliable; religious
// holidays (Eid, Lunar New Year, etc.) vary — ALWAYS confirm
// with the local agent / official calendar before relying on
// them for a laytime statement.
// ============================================================

export type WeekendType = 'sat-sun' | 'fri-sat' | 'sun-only';

export interface Country {
  code: string;
  name: string;
  flag: string;
  weekend: WeekendType;
  ports: string[];       // notable hub ports
  holidays: Holiday[];
}

export interface Holiday {
  date: string;          // YYYY-MM-DD
  name: string;
  approx?: boolean;      // religious / movable feast — confirm locally
}

export const WEEKEND_LABEL: Record<WeekendType, string> = {
  'sat-sun': 'Saturday – Sunday',
  'fri-sat': 'Friday – Saturday',
  'sun-only': 'Sunday only',
};

// weekend day-of-week sets (0 = Sunday ... 6 = Saturday)
export const WEEKEND_DAYS: Record<WeekendType, number[]> = {
  'sat-sun': [6, 0],
  'fri-sat': [5, 6],
  'sun-only': [0],
};

export const COUNTRIES: Country[] = [
  {
    code: 'TR',
    name: 'Türkiye',
    flag: '🇹🇷',
    weekend: 'sat-sun',
    ports: ['Istanbul (Ambarlı)', 'Tuzla', 'Yarımca', 'Mersin', 'İzmir', 'Gemlik'],
    holidays: [
      { date: '2026-01-01', name: "New Year's Day" },
      { date: '2026-03-20', name: 'Eid al-Fitr (Ramazan Bayramı) — day 1', approx: true },
      { date: '2026-03-21', name: 'Eid al-Fitr — day 2', approx: true },
      { date: '2026-03-22', name: 'Eid al-Fitr — day 3', approx: true },
      { date: '2026-04-23', name: "National Sovereignty & Children's Day" },
      { date: '2026-05-01', name: 'Labour Day' },
      { date: '2026-05-19', name: 'Commemoration of Atatürk, Youth & Sports Day' },
      { date: '2026-05-27', name: 'Eid al-Adha (Kurban Bayramı) — day 1', approx: true },
      { date: '2026-05-28', name: 'Eid al-Adha — day 2', approx: true },
      { date: '2026-05-29', name: 'Eid al-Adha — day 3', approx: true },
      { date: '2026-05-30', name: 'Eid al-Adha — day 4', approx: true },
      { date: '2026-07-15', name: 'Democracy & National Unity Day' },
      { date: '2026-08-30', name: 'Victory Day' },
      { date: '2026-10-29', name: 'Republic Day' },
    ],
  },
  {
    code: 'SG',
    name: 'Singapore',
    flag: '🇸🇬',
    weekend: 'sat-sun',
    ports: ['Singapore (PSA)', 'Jurong'],
    holidays: [
      { date: '2026-01-01', name: "New Year's Day" },
      { date: '2026-02-17', name: 'Chinese New Year — day 1', approx: true },
      { date: '2026-02-18', name: 'Chinese New Year — day 2', approx: true },
      { date: '2026-03-21', name: 'Hari Raya Puasa', approx: true },
      { date: '2026-04-03', name: 'Good Friday', approx: true },
      { date: '2026-05-01', name: 'Labour Day' },
      { date: '2026-05-27', name: 'Hari Raya Haji', approx: true },
      { date: '2026-05-31', name: 'Vesak Day', approx: true },
      { date: '2026-08-09', name: 'National Day' },
      { date: '2026-11-08', name: 'Deepavali', approx: true },
      { date: '2026-12-25', name: 'Christmas Day' },
    ],
  },
  {
    code: 'AE',
    name: 'UAE',
    flag: '🇦🇪',
    weekend: 'fri-sat',
    ports: ['Jebel Ali', 'Khor Fakkan', 'Fujairah', 'Abu Dhabi (Khalifa)'],
    holidays: [
      { date: '2026-01-01', name: "New Year's Day" },
      { date: '2026-03-20', name: 'Eid al-Fitr — day 1', approx: true },
      { date: '2026-03-21', name: 'Eid al-Fitr — day 2', approx: true },
      { date: '2026-03-22', name: 'Eid al-Fitr — day 3', approx: true },
      { date: '2026-05-26', name: 'Arafat Day', approx: true },
      { date: '2026-05-27', name: 'Eid al-Adha — day 1', approx: true },
      { date: '2026-05-28', name: 'Eid al-Adha — day 2', approx: true },
      { date: '2026-05-29', name: 'Eid al-Adha — day 3', approx: true },
      { date: '2026-06-16', name: 'Islamic New Year', approx: true },
      { date: '2026-08-25', name: "Prophet's Birthday", approx: true },
      { date: '2026-12-01', name: 'Commemoration Day' },
      { date: '2026-12-02', name: 'National Day — day 1' },
      { date: '2026-12-03', name: 'National Day — day 2' },
    ],
  },
  {
    code: 'NL',
    name: 'Netherlands',
    flag: '🇳🇱',
    weekend: 'sat-sun',
    ports: ['Rotterdam', 'Amsterdam'],
    holidays: [
      { date: '2026-01-01', name: "New Year's Day" },
      { date: '2026-04-03', name: 'Good Friday', approx: true },
      { date: '2026-04-05', name: 'Easter Sunday', approx: true },
      { date: '2026-04-06', name: 'Easter Monday', approx: true },
      { date: '2026-04-27', name: "King's Day" },
      { date: '2026-05-05', name: 'Liberation Day' },
      { date: '2026-05-14', name: 'Ascension Day', approx: true },
      { date: '2026-05-25', name: 'Whit Monday', approx: true },
      { date: '2026-12-25', name: 'Christmas Day' },
      { date: '2026-12-26', name: 'Boxing Day' },
    ],
  },
  {
    code: 'DE',
    name: 'Germany',
    flag: '🇩🇪',
    weekend: 'sat-sun',
    ports: ['Hamburg', 'Bremerhaven', 'Wilhelmshaven'],
    holidays: [
      { date: '2026-01-01', name: "New Year's Day" },
      { date: '2026-04-03', name: 'Good Friday', approx: true },
      { date: '2026-04-06', name: 'Easter Monday', approx: true },
      { date: '2026-05-01', name: 'Labour Day' },
      { date: '2026-05-14', name: 'Ascension Day', approx: true },
      { date: '2026-05-25', name: 'Whit Monday', approx: true },
      { date: '2026-10-03', name: 'German Unity Day' },
      { date: '2026-12-25', name: 'Christmas Day' },
      { date: '2026-12-26', name: 'St Stephen / 2nd Christmas Day' },
    ],
  },
  {
    code: 'CN',
    name: 'China',
    flag: '🇨🇳',
    weekend: 'sat-sun',
    ports: ['Shanghai', 'Ningbo-Zhoushan', 'Qingdao', 'Tianjin', 'Shenzhen'],
    holidays: [
      { date: '2026-01-01', name: "New Year's Day" },
      { date: '2026-02-16', name: 'Spring Festival (CNY) — day 1', approx: true },
      { date: '2026-02-17', name: 'Spring Festival — day 2', approx: true },
      { date: '2026-02-18', name: 'Spring Festival — day 3', approx: true },
      { date: '2026-02-19', name: 'Spring Festival — day 4', approx: true },
      { date: '2026-02-20', name: 'Spring Festival — day 5', approx: true },
      { date: '2026-04-05', name: 'Qingming Festival', approx: true },
      { date: '2026-05-01', name: 'Labour Day' },
      { date: '2026-06-19', name: 'Dragon Boat Festival', approx: true },
      { date: '2026-09-25', name: 'Mid-Autumn Festival', approx: true },
      { date: '2026-10-01', name: 'National Day — day 1' },
      { date: '2026-10-02', name: 'National Day — day 2' },
      { date: '2026-10-03', name: 'National Day — day 3' },
    ],
  },
  {
    code: 'KR',
    name: 'South Korea',
    flag: '🇰🇷',
    weekend: 'sat-sun',
    ports: ['Busan', 'Ulsan', 'Incheon', 'Gwangyang'],
    holidays: [
      { date: '2026-01-01', name: "New Year's Day" },
      { date: '2026-02-16', name: 'Seollal (Lunar NY) — day 1', approx: true },
      { date: '2026-02-17', name: 'Seollal — day 2', approx: true },
      { date: '2026-02-18', name: 'Seollal — day 3', approx: true },
      { date: '2026-03-01', name: 'Independence Movement Day' },
      { date: '2026-05-05', name: "Children's Day" },
      { date: '2026-06-06', name: 'Memorial Day' },
      { date: '2026-08-15', name: 'Liberation Day' },
      { date: '2026-09-24', name: 'Chuseok — day 1', approx: true },
      { date: '2026-09-25', name: 'Chuseok — day 2', approx: true },
      { date: '2026-09-26', name: 'Chuseok — day 3', approx: true },
      { date: '2026-10-03', name: 'National Foundation Day' },
      { date: '2026-10-09', name: 'Hangeul Day' },
      { date: '2026-12-25', name: 'Christmas Day' },
    ],
  },
  {
    code: 'PA',
    name: 'Panama',
    flag: '🇵🇦',
    weekend: 'sat-sun',
    ports: ['Balboa', 'Colón / Cristóbal', 'Panama Canal'],
    holidays: [
      { date: '2026-01-01', name: "New Year's Day" },
      { date: '2026-01-09', name: 'Martyrs Day' },
      { date: '2026-02-17', name: 'Carnival Monday', approx: true },
      { date: '2026-02-18', name: 'Carnival Tuesday', approx: true },
      { date: '2026-04-03', name: 'Good Friday', approx: true },
      { date: '2026-05-01', name: 'Labour Day' },
      { date: '2026-11-03', name: 'Separation Day' },
      { date: '2026-11-05', name: 'Colón Day' },
      { date: '2026-11-10', name: 'Los Santos Uprising' },
      { date: '2026-11-28', name: 'Independence from Spain' },
      { date: '2026-12-08', name: "Mothers' Day" },
      { date: '2026-12-25', name: 'Christmas Day' },
    ],
  },
  {
    code: 'BR',
    name: 'Brazil',
    flag: '🇧🇷',
    weekend: 'sat-sun',
    ports: ['Santos', 'Tubarão', 'Paranaguá', 'Itaqui'],
    holidays: [
      { date: '2026-01-01', name: "New Year's Day" },
      { date: '2026-02-16', name: 'Carnival Monday', approx: true },
      { date: '2026-02-17', name: 'Carnival Tuesday', approx: true },
      { date: '2026-04-03', name: 'Good Friday', approx: true },
      { date: '2026-04-21', name: 'Tiradentes Day' },
      { date: '2026-05-01', name: 'Labour Day' },
      { date: '2026-06-04', name: 'Corpus Christi', approx: true },
      { date: '2026-09-07', name: 'Independence Day' },
      { date: '2026-10-12', name: 'Our Lady of Aparecida' },
      { date: '2026-11-02', name: "All Souls' Day" },
      { date: '2026-11-15', name: 'Republic Day' },
      { date: '2026-12-25', name: 'Christmas Day' },
    ],
  },
  {
    code: 'US',
    name: 'United States',
    flag: '🇺🇸',
    weekend: 'sat-sun',
    ports: ['Houston', 'New Orleans', 'Los Angeles / Long Beach', 'New York'],
    holidays: [
      { date: '2026-01-01', name: "New Year's Day" },
      { date: '2026-01-19', name: 'Martin Luther King Jr. Day' },
      { date: '2026-02-16', name: "Presidents' Day" },
      { date: '2026-05-25', name: 'Memorial Day' },
      { date: '2026-06-19', name: 'Juneteenth' },
      { date: '2026-07-03', name: 'Independence Day (observed)' },
      { date: '2026-09-07', name: 'Labor Day' },
      { date: '2026-11-11', name: 'Veterans Day' },
      { date: '2026-11-26', name: 'Thanksgiving' },
      { date: '2026-12-25', name: 'Christmas Day' },
    ],
  },
  {
    code: 'GR',
    name: 'Greece',
    flag: '🇬🇷',
    weekend: 'sat-sun',
    ports: ['Piraeus', 'Thessaloniki'],
    holidays: [
      { date: '2026-01-01', name: "New Year's Day" },
      { date: '2026-01-06', name: 'Epiphany' },
      { date: '2026-02-23', name: 'Clean Monday', approx: true },
      { date: '2026-03-25', name: 'Independence Day' },
      { date: '2026-04-10', name: 'Orthodox Good Friday', approx: true },
      { date: '2026-04-13', name: 'Orthodox Easter Monday', approx: true },
      { date: '2026-05-01', name: 'Labour Day' },
      { date: '2026-06-01', name: 'Whit Monday', approx: true },
      { date: '2026-08-15', name: 'Assumption of Mary' },
      { date: '2026-10-28', name: 'Ohi Day' },
      { date: '2026-12-25', name: 'Christmas Day' },
      { date: '2026-12-26', name: 'Boxing Day' },
    ],
  },
  {
    code: 'BE',
    name: 'Belgium',
    flag: '🇧🇪',
    weekend: 'sat-sun',
    ports: ['Antwerp', 'Zeebrugge', 'Ghent'],
    holidays: [
      { date: '2026-01-01', name: "New Year's Day" },
      { date: '2026-04-06', name: 'Easter Monday', approx: true },
      { date: '2026-05-01', name: 'Labour Day' },
      { date: '2026-05-14', name: 'Ascension Day', approx: true },
      { date: '2026-05-25', name: 'Whit Monday', approx: true },
      { date: '2026-07-21', name: 'National Day' },
      { date: '2026-08-15', name: 'Assumption' },
      { date: '2026-11-01', name: "All Saints' Day" },
      { date: '2026-11-11', name: 'Armistice Day' },
      { date: '2026-12-25', name: 'Christmas Day' },
    ],
  },
  {
    code: 'EG',
    name: 'Egypt',
    flag: '🇪🇬',
    weekend: 'fri-sat',
    ports: ['Suez Canal', 'Port Said', 'Alexandria', 'Damietta'],
    holidays: [
      { date: '2026-01-07', name: 'Coptic Christmas' },
      { date: '2026-01-25', name: 'Revolution Day / Police Day' },
      { date: '2026-03-20', name: 'Eid al-Fitr — day 1', approx: true },
      { date: '2026-03-21', name: 'Eid al-Fitr — day 2', approx: true },
      { date: '2026-03-22', name: 'Eid al-Fitr — day 3', approx: true },
      { date: '2026-04-13', name: 'Sham El-Nessim', approx: true },
      { date: '2026-04-25', name: 'Sinai Liberation Day' },
      { date: '2026-05-01', name: 'Labour Day' },
      { date: '2026-05-27', name: 'Eid al-Adha — day 1', approx: true },
      { date: '2026-05-28', name: 'Eid al-Adha — day 2', approx: true },
      { date: '2026-06-16', name: 'Islamic New Year', approx: true },
      { date: '2026-06-30', name: 'June 30 Revolution Day' },
      { date: '2026-07-23', name: 'Revolution Day' },
      { date: '2026-10-06', name: 'Armed Forces Day' },
    ],
  },
  {
    code: 'ES',
    name: 'Spain',
    flag: '🇪🇸',
    weekend: 'sat-sun',
    ports: ['Algeciras', 'Valencia', 'Barcelona', 'Bilbao'],
    holidays: [
      { date: '2026-01-01', name: "New Year's Day" },
      { date: '2026-01-06', name: 'Epiphany' },
      { date: '2026-04-03', name: 'Good Friday', approx: true },
      { date: '2026-05-01', name: 'Labour Day' },
      { date: '2026-08-15', name: 'Assumption' },
      { date: '2026-10-12', name: 'National Day' },
      { date: '2026-11-01', name: "All Saints' Day" },
      { date: '2026-12-06', name: 'Constitution Day' },
      { date: '2026-12-08', name: 'Immaculate Conception' },
      { date: '2026-12-25', name: 'Christmas Day' },
    ],
  },
];
