// ============================================================
// SERVICES CONFIG — All maritime service categories for SEO
// Used by /ports/[port]/[service] programmatic pages
// ============================================================

export interface ServiceCategory {
  slug: string;           // URL slug (e.g. 'ship-agent')
  key: string;            // Internal key matching provider svc[] (e.g. 'agent')
  label: string;          // Display name (e.g. 'Ship Agent')
  shortLabel: string;     // Short version for tight spaces
  type: 'agent' | 'chandler' | 'service'; // Provider type filter
  svcKey?: string;        // Specific service filter (for type=service)
  description: string;    // Short description
  longDescription: string;// Full SEO description
  keywords: string[];     // SEO keywords
}

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  // ===== MAIN CATEGORIES (matches type filter) =====
  {
    slug: 'ship-agent',
    key: 'agent',
    label: 'Ship Agent',
    shortLabel: 'Ship Agent',
    type: 'agent',
    description: 'Port agency, husbandry, customs clearance, crew change coordination',
    longDescription: 'Verified ship agents providing full port agency services including pre-arrival notification, customs clearance, immigration, pilotage coordination, bunker call handling, crew change coordination, supplies arrangement, and 24/7 husbandry services for all vessel types.',
    keywords: ['ship agent', 'port agency', 'husbandry', 'shipping agency', 'port agent'],
  },
  {
    slug: 'shipchandler',
    key: 'chandler',
    label: 'Shipchandler',
    shortLabel: 'Shipchandler',
    type: 'chandler',
    description: 'Fresh provisions, bonded stores, deck and engine stores, spare parts',
    longDescription: 'Premium shipchandlers providing fresh and frozen provisions, bonded stores (alcohol, tobacco), deck stores, engine room supplies, cabin stores, safety equipment, medical supplies, and technical spares with 24/7 delivery to anchorage and alongside.',
    keywords: ['shipchandler', 'ship chandler', 'ship supplies', 'vessel provisions', 'marine supplies'],
  },

  // ===== MARINE SERVICES (matches svc filter) =====
  {
    slug: 'main-engine-service',
    key: 'service',
    label: 'Main & Auxiliary Engine Service',
    shortLabel: 'Engine Service',
    type: 'service',
    svcKey: 'engine',
    description: 'Main engine overhaul, top overhaul, performance optimization, auxiliary engine service',
    longDescription: 'Certified marine engine service companies for all major manufacturers (MAN Energy Solutions, Wärtsilä, Hyundai HiMSEN, Mitsubishi, MTU). Services include main engine top overhaul, performance optimization, troubleshooting, auxiliary engine service, and emergency repair.',
    keywords: ['marine engine service', 'main engine repair', 'auxiliary engine', 'MAN service', 'Wartsila service'],
  },
  {
    slug: 'refrigeration-hvac',
    key: 'service',
    label: 'Refrigeration & HVAC Service',
    shortLabel: 'Refrigeration & HVAC',
    type: 'service',
    svcKey: 'refrigeration',
    description: 'Reefer container service, vessel HVAC, cold storage maintenance',
    longDescription: 'Marine refrigeration and HVAC service companies specializing in reefer container service, vessel air conditioning systems, cold storage maintenance, reefer cargo monitoring, and emergency response.',
    keywords: ['marine refrigeration', 'reefer service', 'vessel HVAC', 'cold storage'],
  },
  {
    slug: 'electrical-automation',
    key: 'service',
    label: 'Electrical & Automation Service',
    shortLabel: 'Electrical & Automation',
    type: 'service',
    svcKey: 'electrical',
    description: 'Marine electrical, automation systems, control panel service',
    longDescription: 'Marine electrical and automation service providers covering switchboard maintenance, control system service, automation panels, motor service, generator maintenance, and emergency electrical repair.',
    keywords: ['marine electrical', 'automation service', 'switchboard service', 'control panel'],
  },
  {
    slug: 'navigation-communication',
    key: 'service',
    label: 'Navigation & Communication Service',
    shortLabel: 'Nav & Comm',
    type: 'service',
    svcKey: 'navigation',
    description: 'Navigation equipment, communication systems, bridge electronics',
    longDescription: 'Navigation and communication equipment service for radar, gyrocompass, autopilot, AIS, GPS, VDR, and bridge integrated systems. Major vendor service partners for Furuno, JRC, Sperry Marine, and others.',
    keywords: ['navigation equipment service', 'bridge electronics', 'AIS service', 'radar service'],
  },
  {
    slug: 'underwater-diving',
    key: 'service',
    label: 'Underwater Diving Service',
    shortLabel: 'Underwater Diving',
    type: 'service',
    svcKey: 'diving',
    description: 'Class-approved diving, IWS, propeller polishing, hull inspection',
    longDescription: 'Class-approved commercial diving services including in-water surveys (IWS/UWILD), propeller polishing, hull inspection, anode replacement, sea chest cleaning, and emergency underwater repair.',
    keywords: ['underwater diving', 'IWS survey', 'propeller polishing', 'hull inspection diving'],
  },
  {
    slug: 'hull-cleaning',
    key: 'service',
    label: 'Hull, Propeller & Rudder Service',
    shortLabel: 'Hull Cleaning',
    type: 'service',
    svcKey: 'hull',
    description: 'Hull cleaning, propeller polishing, biofouling removal',
    longDescription: 'Hull cleaning and propeller polishing services for fuel efficiency. Class-approved underwater hull cleaning, biofouling removal, propeller polishing, rudder inspection, and IMO biofouling guideline compliance.',
    keywords: ['hull cleaning', 'propeller polishing', 'biofouling removal', 'underwater hull cleaning'],
  },
  {
    slug: 'crane-hatch-covers',
    key: 'service',
    label: 'Crane & Hatch Cover Service',
    shortLabel: 'Crane & Hatch',
    type: 'service',
    svcKey: 'crane',
    description: 'Deck crane service, hatch cover maintenance and testing',
    longDescription: 'Deck crane service and hatch cover maintenance including load testing, hydraulic system service, wire rope renewal, hatch cover hose tests, and ultrasonic hatch tightness tests.',
    keywords: ['crane service', 'hatch cover service', 'deck crane', 'hatch cover testing'],
  },
  {
    slug: 'welding-fabrication',
    key: 'service',
    label: 'Welding & Fabrication Service',
    shortLabel: 'Welding',
    type: 'service',
    svcKey: 'welding',
    description: 'Class-approved welding, structural fabrication, steel repair',
    longDescription: 'Class-approved welding and fabrication services with certified welders for hull repair, structural reinforcement, piping welding, stainless steel fabrication, and emergency hot work.',
    keywords: ['marine welding', 'class approved welding', 'steel fabrication', 'structural repair'],
  },
  {
    slug: 'mooring-rigging',
    key: 'service',
    label: 'Mooring & Rigging Service',
    shortLabel: 'Mooring & Rigging',
    type: 'service',
    svcKey: 'mooring',
    description: 'Mooring lines, rigging service, wire rope inspection',
    longDescription: 'Mooring and rigging services including mooring line inspection, wire rope renewal, rigging certification, deck equipment service, and load testing.',
    keywords: ['mooring service', 'rigging service', 'wire rope service'],
  },
  {
    slug: 'classification-survey',
    key: 'service',
    label: 'Classification Survey',
    shortLabel: 'Class Survey',
    type: 'service',
    svcKey: 'survey',
    description: 'Class survey support for DNV, LR, ABS, BV, NK, RINA',
    longDescription: 'Classification society survey support including annual surveys, intermediate surveys, special surveys, and class renewal. Services aligned with DNV, Lloyd\'s Register, ABS, Bureau Veritas, ClassNK, RINA, Korean Register, and CCS procedures.',
    keywords: ['classification survey', 'class survey', 'DNV survey', 'LR survey', 'ABS survey'],
  },
  {
    slug: 'ndt-testing',
    key: 'service',
    label: 'Non-Destructive Testing',
    shortLabel: 'NDT',
    type: 'service',
    svcKey: 'ndt',
    description: 'Ultrasonic testing, magnetic particle, dye penetrant, radiography',
    longDescription: 'Non-destructive testing services including ultrasonic thickness measurement (UTM), magnetic particle inspection (MPI), dye penetrant testing (DPT), radiography, and class-approved NDT documentation.',
    keywords: ['NDT services', 'ultrasonic testing', 'thickness measurement', 'UTM survey'],
  },
  {
    slug: 'firefighting-safety',
    key: 'service',
    label: 'Firefighting & Safety Service',
    shortLabel: 'Firefighting',
    type: 'service',
    svcKey: 'firefighting',
    description: 'Fire extinguisher service, CO2 system, fire detection',
    longDescription: 'Marine firefighting equipment service including fire extinguisher refilling and certification, CO2 fixed firefighting system service, fire detection system maintenance, and SOLAS compliance support.',
    keywords: ['fire extinguisher service', 'CO2 system', 'fire detection', 'SOLAS firefighting'],
  },
  {
    slug: 'bwts-ballast-water',
    key: 'service',
    label: 'Ballast Water Treatment Service',
    shortLabel: 'BWTS Service',
    type: 'service',
    svcKey: 'ballast',
    description: 'BWTS service, UV lamp replacement, BWMC compliance',
    longDescription: 'Ballast Water Treatment System (BWTS) service for all major manufacturers — Alfa Laval PureBallast, Optimarin, Wärtsilä Aquarius, Hyde Marine, Techcross. Annual service, UV lamp replacement, sensor calibration, sampling, and BWMC/USCG BWMS compliance.',
    keywords: ['BWTS service', 'ballast water treatment', 'BWMC compliance', 'UV lamp replacement'],
  },
  {
    slug: 'hydraulics-service',
    key: 'service',
    label: 'Hydraulics Service',
    shortLabel: 'Hydraulics',
    type: 'service',
    svcKey: 'hydraulics',
    description: 'Hydraulic system service, cylinder repair, oil change',
    longDescription: 'Marine hydraulics service for steering gear, deck machinery, cargo handling equipment, hatch cover hydraulics, cylinder repair, hydraulic oil testing, and system commissioning.',
    keywords: ['marine hydraulics', 'hydraulic service', 'steering gear service'],
  },
  {
    slug: 'boiler-steam-systems',
    key: 'service',
    label: 'Boiler & Steam Systems Service',
    shortLabel: 'Boiler Service',
    type: 'service',
    svcKey: 'boiler',
    description: 'Marine boiler service, EGE cleaning, tube renewal, refractory repair',
    longDescription: 'Marine boiler service for Aalborg (Alfa Laval), Mitsubishi, Kangrim, Saacke, Miura, and other manufacturers. Annual service, exhaust gas economiser (EGE) cleaning, tube renewal, refractory repair, safety valve testing, and combustion tuning.',
    keywords: ['marine boiler service', 'Aalborg boiler', 'EGE cleaning', 'boiler tube renewal'],
  },
  {
    slug: 'painting-blasting',
    key: 'service',
    label: 'Painting & Blasting',
    shortLabel: 'Painting',
    type: 'service',
    svcKey: 'painting',
    description: 'Marine painting, surface preparation, anti-fouling coating',
    longDescription: 'Marine painting and blasting services including surface preparation, anti-fouling coating application, hull painting, tank coating, deck painting, and class-approved paint systems.',
    keywords: ['marine painting', 'anti-fouling', 'hull painting', 'blasting service'],
  },
  {
    slug: 'sewage-marpol',
    key: 'service',
    label: 'Sewage & MARPOL Service',
    shortLabel: 'Sewage & MARPOL',
    type: 'service',
    svcKey: 'sewage',
    description: 'Sewage treatment, oily water separator, MARPOL compliance',
    longDescription: 'Sewage treatment plant service, oily water separator (OWS) service, MARPOL Annex IV/V compliance, sewage discharge testing, and certification.',
    keywords: ['sewage treatment', 'MARPOL service', 'OWS service'],
  },
  {
    slug: 'liferaft-lsa',
    key: 'service',
    label: 'Liferaft & LSA Service',
    shortLabel: 'Liferaft & LSA',
    type: 'service',
    svcKey: 'liferaft',
    description: 'Liferaft annual service, LSA equipment certification',
    longDescription: 'Liferaft annual service and LSA (Life-Saving Appliance) equipment service including liferaft inspection, hydrostatic release certification, lifeboat maintenance, lifejacket service, and SOLAS LSA compliance.',
    keywords: ['liferaft service', 'LSA service', 'lifeboat maintenance', 'SOLAS LSA'],
  },
  {
    slug: 'crew-change-logistics',
    key: 'service',
    label: 'Crew Change & Logistics',
    shortLabel: 'Crew Change',
    type: 'service',
    svcKey: 'crew',
    description: 'Crew change coordination, hotel, transport, visa support',
    longDescription: 'Crew change coordination services including airport transfer, hotel accommodation, immigration support, visa assistance, manning agency liaison, and PCR/health certification logistics.',
    keywords: ['crew change', 'crew logistics', 'seafarer transport', 'crew change agent'],
  },
  {
    slug: 'bunker-supply',
    key: 'service',
    label: 'Bunker Supply',
    shortLabel: 'Bunker Supply',
    type: 'service',
    svcKey: 'bunker',
    description: 'VLSFO, HSFO, MGO bunker fuel supply',
    longDescription: 'Bunker fuel supply including VLSFO (Very Low Sulfur Fuel Oil), HSFO with scrubber, MGO (Marine Gas Oil), MDO, biofuels, and LNG bunkering. Quality survey support and ISO 8217 compliance.',
    keywords: ['bunker supply', 'VLSFO bunker', 'marine fuel', 'MGO supply'],
  },
  {
    slug: 'lubricant-supply',
    key: 'service',
    label: 'Lubricant Supply',
    shortLabel: 'Lubricant',
    type: 'service',
    svcKey: 'lubricant',
    description: 'Marine lubricants, engine oil, hydraulic oil supply',
    longDescription: 'Marine lubricant supply including cylinder oil, system oil, gear oil, hydraulic oil, and grease for all major engine manufacturers. Class-approved products with delivery certificates.',
    keywords: ['marine lubricant', 'cylinder oil supply', 'hydraulic oil'],
  },
  {
    slug: 'fresh-water-supply',
    key: 'service',
    label: 'Fresh Water Supply',
    shortLabel: 'Fresh Water',
    type: 'service',
    svcKey: 'freshwater',
    description: 'Potable water bunkering for vessels',
    longDescription: 'Fresh water supply (potable water bunkering) services including barge delivery, alongside supply, water quality testing, and certificate documentation.',
    keywords: ['fresh water supply', 'potable water', 'water bunkering'],
  },
  {
    slug: 'garbage-sludge-disposal',
    key: 'service',
    label: 'Garbage & Sludge Disposal',
    shortLabel: 'Garbage Disposal',
    type: 'service',
    svcKey: 'garbage',
    description: 'Garbage collection, sludge disposal, MARPOL compliance',
    longDescription: 'Vessel garbage collection and sludge disposal services compliant with MARPOL Annex V. Includes plastic separation, food waste, oily sludge, hazardous waste, and disposal certificates.',
    keywords: ['garbage disposal', 'sludge disposal', 'MARPOL Annex V'],
  },
  {
    slug: 'tank-cleaning',
    key: 'service',
    label: 'Tank Cleaning',
    shortLabel: 'Tank Cleaning',
    type: 'service',
    svcKey: 'tank',
    description: 'Cargo tank cleaning, gas-free preparation, COW',
    longDescription: 'Tank cleaning services for tankers including cargo tank cleaning, crude oil washing (COW), tank preparation for next cargo, gas-free preparation, and certification.',
    keywords: ['tank cleaning', 'cargo tank cleaning', 'COW service', 'gas free preparation'],
  },
  {
    slug: 'slop-bilge-disposal',
    key: 'service',
    label: 'Slop & Bilge Disposal',
    shortLabel: 'Slop & Bilge',
    type: 'service',
    svcKey: 'slop',
    description: 'Slop water and bilge water disposal services',
    longDescription: 'Slop water and oily bilge water disposal services compliant with MARPOL Annex I. Includes barge collection, certificate documentation, and approved reception facilities.',
    keywords: ['slop disposal', 'bilge water disposal', 'MARPOL Annex I'],
  },
  {
    slug: 'cargo-hold-cleaning',
    key: 'service',
    label: 'Cargo Hold Cleaning',
    shortLabel: 'Hold Cleaning',
    type: 'service',
    svcKey: 'holdcleaning',
    description: 'Bulk carrier cargo hold cleaning, hold preparation',
    longDescription: 'Cargo hold cleaning services for bulk carriers including hold sweeping, washing, lime washing, hold inspection, and preparation for next cargo with surveyor coordination.',
    keywords: ['cargo hold cleaning', 'bulk carrier hold cleaning', 'hold preparation'],
  },
  {
    slug: 'lashing-securing',
    key: 'service',
    label: 'Lashing & Securing',
    shortLabel: 'Lashing',
    type: 'service',
    svcKey: 'lashing',
    description: 'Container lashing, cargo securing, project cargo',
    longDescription: 'Container lashing and cargo securing services including lashing inspection, securing equipment supply, project cargo lashing, and CSM (Cargo Securing Manual) compliance.',
    keywords: ['container lashing', 'cargo securing', 'CSM compliance'],
  },
  {
    slug: 'anchor-chain-service',
    key: 'service',
    label: 'Anchor & Chain Service',
    shortLabel: 'Anchor & Chain',
    type: 'service',
    svcKey: 'anchor',
    description: 'Anchor inspection, chain renewal, windlass service',
    longDescription: 'Anchor and chain service including anchor inspection, chain measurement, chain renewal, anchor windlass service, brake testing, and class-approved certification.',
    keywords: ['anchor service', 'chain renewal', 'windlass service'],
  },
  {
    slug: 'pilot-ladder-inspection',
    key: 'service',
    label: 'Pilot Ladder Inspection',
    shortLabel: 'Pilot Ladder',
    type: 'service',
    svcKey: 'pilotladder',
    description: 'Pilot ladder inspection and SOLAS compliance',
    longDescription: 'Pilot ladder inspection services including SOLAS Chapter V compliance check, IMO MSC.1/Circ.1428 verification, replacement, and certification documentation.',
    keywords: ['pilot ladder inspection', 'SOLAS pilot ladder'],
  },
  {
    slug: 'gas-free-certification',
    key: 'service',
    label: 'Gas Free Certification',
    shortLabel: 'Gas Free',
    type: 'service',
    svcKey: 'gasfree',
    description: 'Gas free certificate for hot work, tank entry',
    longDescription: 'Gas free certification services for hot work permits, tank entry, enclosed space entry, and class-approved gas measurement documentation.',
    keywords: ['gas free certificate', 'tank entry certificate', 'hot work permit'],
  },
  {
    slug: 'gmdss-radio-survey',
    key: 'service',
    label: 'Radio / GMDSS Survey',
    shortLabel: 'GMDSS Survey',
    type: 'service',
    svcKey: 'gmdss',
    description: 'Annual GMDSS radio survey, EPIRB battery, SART service',
    longDescription: 'GMDSS radio survey services including annual mandatory radio survey under SOLAS Chapter IV, EPIRB battery replacement, SART operational testing, Inmarsat and Iridium service, VHF DSC verification, and class-approved radio surveyors.',
    keywords: ['GMDSS radio survey', 'annual radio survey', 'EPIRB service', 'SART service'],
  },
  {
    slug: 'ecdis-service',
    key: 'service',
    label: 'ECDIS Update Service',
    shortLabel: 'ECDIS Service',
    type: 'service',
    svcKey: 'ecdis',
    description: 'ENC chart update, ECDIS software upgrade, performance check',
    longDescription: 'ECDIS service for Furuno, JRC, Sperry Marine, Wärtsilä/Transas, Kongsberg systems. Routine ENC chart updates, software upgrades, annual performance checks, commissioning, and class survey support.',
    keywords: ['ECDIS service', 'ENC chart update', 'ECDIS software upgrade', 'paperless navigation'],
  },
  {
    slug: 'imo-flag-documentation',
    key: 'service',
    label: 'IMO / Flag Documentation',
    shortLabel: 'IMO Documentation',
    type: 'service',
    svcKey: 'imo',
    description: 'Flag state documentation, IMO compliance support',
    longDescription: 'Flag state documentation services including IMO numbering, vessel registration, flag state correspondence, certificate renewal, and regulatory compliance documentation.',
    keywords: ['IMO documentation', 'flag state documentation', 'vessel certificates'],
  },
  {
    slug: 'pest-control',
    key: 'service',
    label: 'Pest Control & Fumigation',
    shortLabel: 'Pest Control',
    type: 'service',
    svcKey: 'pestcontrol',
    description: 'Vessel fumigation, pest control, rodent control',
    longDescription: 'Marine pest control and fumigation services including cargo fumigation, vessel rodent control, insect treatment, deratting certificates, and IMO compliance.',
    keywords: ['vessel fumigation', 'pest control', 'deratting certificate'],
  },
];

// Helper: get service category by slug
export function getServiceBySlug(slug: string): ServiceCategory | null {
  return SERVICE_CATEGORIES.find(s => s.slug === slug) || null;
}

// Helper: get all service slugs
export function getAllServiceSlugs(): string[] {
  return SERVICE_CATEGORIES.map(s => s.slug);
}
